### ISSUE TITLE
How to for facebook and linked in?

### ISSUE THREAD

**Issue by badarotti** [wangvisual/ldapinfo#24]
Hi is there a step by step howto setup the facebook and Linked in tokens? the help page only has what seems to me an old version of linked in. ..

Thanks

**Comment by wangvisual** [comment]
The home page 'https://addons.mozilla.org/en-US/thunderbird/addon/ldapinfoshow/' has an update.
UPDATE: March 9 2015, LinkedIn decided to no longer support Microsoft Outlook Social Connector anymore, so this addon can't support Linkedin also.

**Comment by gorkarodrigo** [comment]
Hi there,

Are you planning to add this feature again?

It would be amazing!

Thanks & Regards

**Comment by chris001** [comment]
@wangvisual 
If linkedin is taking their profile pictures offline, then maybe this add-on should cache the profile pictures forever, and only update them if/when the fetching works again, if/when service goes back online (possibly never).
It would be very disappointing to have had the profile pictures of many linkedin contacts, and then they all become broken images, because the extension didn't cache them securely and permanently.

**Comment by wangvisual** [comment]
facebook and linkedin don't provide API anymore.

**Comment by chris001** [comment]
@wangvisual 
There's an easy way to get facebook profile pic using facebook javascript sdk and html.
1. Login to facebook thru facebook javascript sdk.
2. Get this URL 
`https://m.facebook.com/search/?query=email_id%40email_domain.com`
3. You get back the person's name, user's profile picture URL, and user's facebook profile page url, from the returned html.
